### ISSUE TITLE
'too many arguments:  in Contract constructor'

### ISSUE THREAD

**Issue by digitalftl** [yuichiroaoki/poly-flash#1]
Hi there, I really appreciate you've made this open-source, really good work.

I'm new into this, I've been watching quite a few tutorials on how to deploy the contract with hardhat on mainnet.
I believe I managed to config hardhat.configs for the mainnet, but when I run the command I get this error.

Would you be kind to guide me? What do I need to do?

```
PS D:\Arbitrage\poly-flash-main> npx hardhat run scripts/sample-script.ts --network polygon
No need to generate any newer typings.
Nothing to compile
No need to generate any newer typings.
Error: too many arguments:  in Contract constructor (count=1, expectedCount=0, code=UNEXPECTED_ARGUMENT, version=contracts/5.5.0)
    at Logger.makeError (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at Logger.checkArgumentCount (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\logger\src.ts\index.ts:303:18)
    at ContractFactory.getDeployTransaction (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\contracts\src.ts\index.ts:1206:16)
    at ContractFactory.<anonymous> (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\contracts\src.ts\index.ts:1234:53)
    at step (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (D:\Arbitrage\poly-flash-main\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'too many arguments:  in Contract constructor',
  code: 'UNEXPECTED_ARGUMENT',
  count: 1,
  expectedCount: 0
}
```

Thank you!

**Comment by yuichiroaoki** [comment]
Hi, I'm glad that you like it!

Have you changed scripts/sample-script.ts ??
Could you show me your scripts/sample-script.ts?? Also the smart contract you want to deploy??

**Comment by digitalftl** [comment]
Hi, yes I set Flashloan in sample-scripts.ts.
Do I need to do something else?

```// We require the Hardhat Runtime Environment explicitly here. This is optional
// but useful for running the script in a standalone fashion through `node <script>`.
//
// When running the script with `hardhat run <script>` you'll find the Hardhat
// Runtime Environment's members available in the global scope.
import { run, ethers } from "hardhat";

const ETHERSCAN_TX_URL = "https://polygonscan.com/address/";

async function main() {
  // Hardhat always runs the compile task when running scripts with its command
  // line interface.
  //
  // If this script is run directly using `node` you may want to call compile
  // manually to make sure everything is compiled
  await run("compile");

  // We get the contract to deploy
  const Greeter = await ethers.getContractFactory("Flashloan");
  const greeter = await Greeter.deploy("Hello, Hardhat!");
  const message = await greeter.greet();

  await greeter.setGreeting("Hola, mundo!");
  const changed_message = await greeter.greet();
  console.log({ message, changed_message });

  await greeter.deployed();

  console.log("Greeter deployed to:", greeter.address);

  console.log(
    `You did it! View your tx here: ${ETHERSCAN_TX_URL}${greeter.deployTransaction.hash}`
  );
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

**Comment by yuichiroaoki** [comment]
You are passing an argument ```Hello, Flashloan``` to the deploy function, which you are not supposed to.

It should be like the following code: 

```typescript

import { ethers, run } from 'hardhat';

async function main() {
  await run('compile');
  const Flashloan = await ethers.getContractFactory('Flashloan');
  const flashloan = await Flashloan.deploy();  // Flashloan.sol deploy function takes no arguments

  console.log(`FlashBot deployed to ${flashloan.address}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```
Notice this Flashloan contract does not have a constructor that takes one parameter.

https://github.com/yuichiroaoki/poly-flash/blob/main/contracts/Flashloan.sol

While this hardhat default Greeter contract has a constructor that takes one string parameter.

https://github.com/yuichiroaoki/poly-flash/blob/8bf493e075b11fcbefa09daa003544a6c0056183/contracts/Greeter.sol#L7-L14

That's why when you deploy this Greeter contract, you pass a string, ```Hello, Hardhat!``` to the deploy function.

https://github.com/yuichiroaoki/poly-flash/blob/8bf493e075b11fcbefa09daa003544a6c0056183/scripts/sample-script.ts#L18-L20

Hope this makes sense😄

**Comment by digitalftl** [comment]
``Yes, it does make sense.

I've got 2 more questions.
1. Do I need to verify the contract?
2.  Does the bot have any console log?


Because I've started the bot, nothing happens, I see in the alchemy dashboard that there is only one request made every few seconds.
```
eth_chainId

```

Thank you so much for your patience.

**Comment by yuichiroaoki** [comment]
1. No, people usually verify their contracts so that everyone can use it like when they build a new Defi protocol.
If you just want use it personally, I think don't have to.

2. Unless there's some errors fetching data from 1inch API or the bot finds an arbitrage, I think it doesn't show any console.log messages.

I think I need to update the docs and code, because you can't tell if the bot running properly or not. 

The error message you got means probably the bot successfully sent a request to 1inch API, but 1inch failed to respond price data.
